kind: Service
apiVersion: v1
metadata:
  name: csi-azuredisk-provisioner
  namespace: {{ .Release.Namespace }}
{{ include "adcd.labels" . | indent 2 }}
    app: csi-azuredisk-provisioner
spec:
  selector:
    app: csi-azuredisk-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-azuredisk-provisioner
  namespace: {{ .Release.Namespace }}
{{ include "adcd.labels" . | indent 2 }}
spec:
  serviceName: "csi-azuredisk-provisioner"
  replicas: 1
  selector:
    matchLabels:
      app: csi-azuredisk-provisioner
  template:
    metadata:
{{ include "adcd.labels" . | indent 6 }}
        app: csi-azuredisk-provisioner
    spec:
      serviceAccountName: csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.0.1
          args:
            - "--provisioner=disk.csi.azure.com"
            - "--csi-address=$(ADDRESS)"
            - "--connection-timeout=15s"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/disk.csi.azure.com
            type: DirectoryOrCreate
          name: socket-dir
