kind: Service
apiVersion: v1
metadata:
  name: csi-azuredisk-attacher
  namespace: {{ .Release.Namespace }}
{{ include "adcd.labels" . | indent 2 }}
    app: csi-azuredisk-attacher
spec:
  selector:
    app: csi-azuredisk-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-azuredisk-attacher
  namespace: {{ .Release.Namespace }}
{{ include "adcd.labels" . | indent 2 }}
    app: csi-azuredisk-attacher
spec:
  serviceName: "csi-azuredisk-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: csi-azuredisk-attacher
  template:
    metadata:
{{ include "adcd.labels" . | indent 6 }}
        app: csi-azuredisk-attacher
    spec:
      serviceAccountName: csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.1
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/disk.csi.azure.com
            type: DirectoryOrCreate
          name: socket-dir
