{{- if .Values.azuredisk.useV2Driver -}}
---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azvolumes.disk.csi.azure.com
spec:
  group: disk.csi.azure.com
  names:
    kind: AzVolume
    listKind: AzVolumeList
    plural: azvolumes
    singular: azvolume
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AzVolume is a specification for a AzVolume resource
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AzVolumeSpec is the spec for a AzVolume resource
            properties:
              maxMountReplicaCount:
                type: integer
              underlyingVolume:
                type: string
            required:
            - maxMountReplicaCount
            - underlyingVolume
            type: object
          status:
            description: AzVolumeStatus is the status for a AzVolume resource
            properties:
              state:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
{{- end -}}