{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.node }}
  namespace: {{ .Release.Namespace }}
  labels: 
{{ include "azuredisk.labels" . | indent 4 }}
{{- end -}}
