language: go
go_import_path: sigs.k8s.io/azuredisk-csi-driver
dist: bionic

go:
  - "1.13.11"

before_install:
  - GO111MODULE=off go get github.com/mattn/goveralls

script:
  - sudo -E env "PATH=$PATH" go test -covermode=count -coverprofile=profile.cov ./pkg/...
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
  - make container
