
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  name: azvolumes.disk.csi.azure.com
spec:
  group: disk.csi.azure.com
  names:
    kind: AzVolume
    listKind: AzVolumeList
    plural: azvolumes
    singular: azvolume
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AzVolume is a specification for an AzVolume resource
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of an AzVolume. Required.
            properties:
              accessibilityRequirements:
                description: Specifies where the provisioned volume should be accessible
                properties:
                  preferred:
                    items:
                      properties:
                        segments:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                    type: array
                  requisite:
                    items:
                      properties:
                        segments:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                    type: array
                type: object
              capacityRange:
                description: The capacity of the storage
                properties:
                  limit_bytes:
                    description: Volume MUST not be bigger than this. This field is OPTIONAL. A value of 0 is equal to an unspecified field value. The value of this field MUST NOT be negative.
                    format: int64
                    type: integer
                  required_bytes:
                    description: Volume MUST be at least this big. This field is OPTIONAL. A value of 0 is equal to an unspecified field value. The value of this field MUST NOT be negative.
                    format: int64
                    type: integer
                type: object
              contentVolumeSource:
                description: ContentVolumeSource for the volume
                properties:
                  content_source:
                    type: integer
                  content_source_id:
                    type: string
                required:
                - content_source
                - content_source_id
                type: object
              maxMountReplicaCount:
                type: integer
              parameters:
                additionalProperties:
                  type: string
                description: Parameters for the volume
                type: object
              secrets:
                additionalProperties:
                  type: string
                description: Secrets for the volume
                type: object
              underlyingVolume:
                description: the disk URI of the underlying volume
                type: string
              volumeCapability:
                description: The capabilities that the volume MUST have
                items:
                  properties:
                    access_details:
                      description: "Specifies what API the volume will be accessed using. One of the following fields MUST be specified. \n Types that are valid to be assigned to AccessType: block, mount"
                      properties:
                        access_type:
                          description: Specifies the access type for the volume.
                          type: integer
                        fs_type:
                          description: The filesystem type. This field is OPTIONAL. An empty string is equal to an unspecified field value.
                          type: string
                        mount_flags:
                          description: The mount options that can be used for the volume. This field is OPTIONAL. `mount_flags` MAY contain sensitive information. Therefore, the CO and the Plugin MUST NOT leak this information to untrusted entities. The total size of this repeated field SHALL NOT exceed 4 KiB.
                          items:
                            type: string
                          type: array
                      required:
                      - access_type
                      type: object
                    access_mode:
                      description: This is a REQUIRED field.
                      type: integer
                  required:
                  - access_details
                  - access_mode
                  type: object
                type: array
            required:
            - maxMountReplicaCount
            - underlyingVolume
            - volumeCapability
            type: object
          status:
            description: status represents the current state of AzVolume. Nil status indicates that the underlying volume has not yet been provisioned
            properties:
              error:
                description: Error occured during creation/deletion of volume
                properties:
                  currentNode:
                    description: "NodeName is a type that holds a api.Node's Name identifier. Being a type captures intent and helps make sure that the node name is not confused with similar concepts (the hostname, the cloud provider id, the cloud provider name etc) \n To clarify the various types: \n * Node.Name is the Name field of the Node in the API.  This should be stored in a NodeName.   Unfortunately, because Name is part of ObjectMeta, we can't store it as a NodeName at the API level. \n * Hostname is the hostname of the local machine (from uname -n).   However, some components allow the user to pass in a --hostname-override flag,   which will override this in most places. In the absence of anything more meaningful,   kubelet will use Hostname as the Node.Name when it creates the Node. \n * The cloudproviders have the own names: GCE has InstanceName, AWS has InstanceId. \n   For GCE, InstanceName is the Name of an Instance object in the GCE API.  On GCE, Instance.Name becomes the   Hostname, and thus it makes sense also to use it as the Node.Name.  But that is GCE specific, and it is up   to the cloudprovider how to do this mapping. \n   For AWS, the InstanceID is not yet suitable for use as a Node.Name, so we actually use the   PrivateDnsName for the Node.Name.  And this is _not_ always the same as the hostname: if   we are using a custom DHCP domain it won't be."
                    type: string
                  devicePath:
                    type: string
                  errorCode:
                    type: string
                  errorMessage:
                    type: string
                required:
                - currentNode
                - devicePath
                - errorCode
                - errorMessage
                type: object
              phase:
                description: Current phase of the underlying PV
                type: string
              status:
                description: Current status of the AzVolume
                properties:
                  accessible_topology:
                    items:
                      properties:
                        segments:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                    type: array
                  capacity_bytes:
                    format: int64
                    type: integer
                  content_source:
                    properties:
                      content_source:
                        type: integer
                      content_source_id:
                        type: string
                    required:
                    - content_source
                    - content_source_id
                    type: object
                  node_expansion_required:
                    type: boolean
                  parameters:
                    additionalProperties:
                      type: string
                    type: object
                  volume_id:
                    type: string
                required:
                - capacity_bytes
                - node_expansion_required
                - volume_id
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
