apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azuredisk
provisioner: disk.csi.azure.com
parameters:
  skuname: Standard_LRS  #alias: storageaccounttype, available values: Standard_LRS, Premium_LRS, (and StandardSSD_LRS, UltraSSD_LRS are supported from k8s v1.13.0)
  kind: managed # value "dedicated", "shared" are deprecated since it's using unmanaged disk
  cachingMode: ReadOnly
reclaimPolicy: Delete
volumeBindingMode: Immediate
