
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  name: azdrivernodes.disk.csi.azure.com
spec:
  group: disk.csi.azure.com
  names:
    kind: AzDriverNode
    listKind: AzDriverNodeList
    plural: azdrivernodes
    singular: azdrivernode
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Name of the Node which this AzDriverNode object represents.
      jsonPath: .spec.nodeName
      name: NodeName
      type: string
    - description: Indicates if the azure persistent volume driver is ready for new
        pods which use azure persistent volumes.
      jsonPath: .status.readyForVolumeAllocation
      name: ReadyForVolumeAllocation
      type: boolean
    - description: Represents the time stamp at which azure persistent volume driver
        sent a heatbeat.
      jsonPath: .status.lastHeartbeatTime
      name: LastHeartbeatTime
      type: date
    - description: A brief node status message.
      jsonPath: .status.statusMessage
      name: StatusMessage
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: AzDriverNode is a representation of a node, where azure CSI driver
          node plug-in runs.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of a AzDriverNode. Required.
            properties:
              nodeName:
                description: Name of the node which this AzDriverNode represents.
                  Required.
                type: string
            required:
            - nodeName
            type: object
          status:
            description: status represents the current state of AzDriverNode. If this
              is nil or empty, clients should prefer other nodes for persistent volume
              allocations or pod places for pods which use azure persistent volumes.
            properties:
              conditions:
                description: Conditions contains an array of generic AzDriver related
                  health conditions These conditions can be used programmatically
                  to take decisions
                items:
                  description: AzDriverCondition defines condition for the AzDriver
                  properties:
                    lastHeartbeatTime:
                      description: Last time we got an update on a given condition.
                      format: date-time
                      type: string
                    lastTransitionTime:
                      description: Last time the condition transit from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: Human readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: (brief) reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of node condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              lastHeartbeatTime:
                description: LastHeartbeatTime represents the timestamp when a heatbeat
                  was sent by driver node plugin. A recent timestamp means that node-plugin
                  is responsive and is communicating to API server. Clients should
                  not solely reply on LastHeartbeatTime to ascertain node plugin's
                  health state.
                format: date-time
                type: string
              readyForVolumeAllocation:
                description: ReadyForVolumeAllocation tells client whether the node
                  plug-in is ready for volume allocation. If status is not present
                  or ReadyForVolumeAllocation, then clients should prefer other nodes
                  in the clusters for azure persistent volumes\pod placements for
                  pods with azure disks.
                type: boolean
              statusMessage:
                description: StatusMessage is a brief status message regarding nodes
                  health This field should not be used for any decision making in
                  code It is for display/debug purpose only For code logic dependency,
                  use Conditions filed
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
