---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-pv2
provisioner: disk.csi.azure.com
parameters:
  cachingMode: None
  skuName: PremiumV2_LRS
  DiskIOPSReadWrite: "4000"
  DiskMBpsReadWrite: "1000"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
