image:
  azuredisk:
    pullPolicy: Always
  schedulerExtender:
    pullPolicy: Always

serviceAccount:
  controller: csi-azuredisk2-controller-sa
  node: csi-azuredisk2-node-sa 
  snapshotController: csi2-snapshot-controller-sa

rbac:
  name: azuredisk2

controller:
  name: csi-azuredisk2-controller
  metrics:
    port: 29624
  livenessProbe:
    healthPort: 29623

node:
  metrics:
    port: 29625
  livenessProbe:
    healthPort: 29627

snapshot:
  enabled: true
  createCRDs: false
  name: csi-azuredisk2-snapshot-controller
  snapshotController:
    name: csi-azuredisk2-snapshot-controller

driver:
  name: disk2.csi.azure.com

linux:
  dsName: csi-azuredisk2-node 

windows:
  dsName: csi-azuredisk2-node-win

storageClasses:
  enableZRS: true