image:
  azuredisk:
    repository: mcr.microsoft.com/k8s/csi/azuredisk-csi
    tag: latest
    pullPolicy: IfNotPresent
  csiProvisioner:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-provisioner
    tag: v2.1.1
    pullPolicy: IfNotPresent
  csiAttacher:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-attacher
    tag: v3.1.0
    pullPolicy: IfNotPresent
  csiResizer:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-resizer
    tag: v1.1.0
    pullPolicy: IfNotPresent
  livenessProbe:
    repository: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe
    tag: v2.3.0
    pullPolicy: IfNotPresent
  nodeDriverRegistrar:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar
    tag: v2.2.0
    pullPolicy: IfNotPresent

serviceAccount:
  create: true # When true, service accounts will be created for you. Set to false if you want to use your own.
  controller: csi-azuredisk-controller-sa # Name of Service Account to be created or used
  node: csi-azuredisk-node-sa # Name of Service Account to be created or used
  snapshotController: csi-snapshot-controller-sa # Name of Service Account to be created or used

rbac:
  create: true
  name: azuredisk

controller:
  name: csi-azuredisk-controller
  replicas: 2
  metricsPort: 29604
  livenessProbe:
    healthPort: 29602
  runOnMaster: false
  disableAvailabilitySetNodes: true
  provisionerWorkerThreads: 40
  attacherWorkerThreads: 500
  logLevel: 5
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/controlplane"
      operator: "Exists"
      effect: "NoSchedule"

node:
  metricsPort: 29605
  logLevel: 5
  livenessProbe:
    healthPort: 29603

snapshot:
  enabled: false
  name: csi-snapshot-controller
  apiVersion: beta # available values: beta, ga
  image:
    csiSnapshotter:
      repository: mcr.microsoft.com/oss/kubernetes-csi/csi-snapshotter
      tag: v3.0.3
      pullPolicy: IfNotPresent
    csiSnapshotController:
      repository: mcr.microsoft.com/oss/kubernetes-csi/snapshot-controller
      tag: v3.0.3
      pullPolicy: IfNotPresent
  snapshotController:
    name: csi-snapshot-controller
    replicas: 1

feature:
  enableFSGroupPolicy: false

driver:
  name: disk.csi.azure.com
  # maximum number of attachable volumes per node,
  # maximum number is defined according to node instance type by default(-1)
  volumeAttachLimit: -1

linux:
  enabled: true
  dsName: csi-azuredisk-node # daemonset name
  kubelet: /var/lib/kubelet
  distro: debian # available values: debian, fedora
  enablePerfOptimization: true
  tolerations:
    - operator: "Exists"

windows:
  enabled: true
  dsName: csi-azuredisk-node-win # daemonset name
  kubelet: 'C:\var\lib\kubelet'
  image:
    livenessProbe:
      repository: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe
      tag: v2.3.0
      pullPolicy: IfNotPresent
    nodeDriverRegistrar:
      repository: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar
      tag: v2.2.0
      pullPolicy: IfNotPresent
  tolerations:
    - key: "node.kubernetes.io/os"
      operator: "Exists"
      effect: "NoSchedule"

cloud: AzurePublicCloud

## Reference to one or more secrets to be used when pulling images
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
imagePullSecrets: []
# - name: "image-pull-secret"
