image:
  baseRepo: mcr.microsoft.com
  azuredisk:
    repository: /k8s/csi/azuredisk-csi
    tag: latest
    pullPolicy: IfNotPresent
  csiProvisioner:
    repository: /oss/v2/kubernetes-csi/csi-provisioner
    tag: v6.1.1
    pullPolicy: IfNotPresent
  csiAttacher:
    repository: /oss/v2/kubernetes-csi/csi-attacher
    tag: v4.11.0
    pullPolicy: IfNotPresent
  csiResizer:
    repository: /oss/v2/kubernetes-csi/csi-resizer
    tag: v2.1.0
    pullPolicy: IfNotPresent
  livenessProbe:
    repository: /oss/v2/kubernetes-csi/livenessprobe
    tag: v2.18.0
    pullPolicy: IfNotPresent
  nodeDriverRegistrar:
    repository: /oss/v2/kubernetes-csi/csi-node-driver-registrar
    tag: v2.16.0
    pullPolicy: IfNotPresent

serviceAccount:
  create: true # When true, service accounts will be created for you. Set to false if you want to use your own.
  controller: csi-azuredisk-controller-sa # Name of Service Account to be created or used
  node: csi-azuredisk-node-sa # Name of Service Account to be created or used
  snapshotController: csi-snapshot-controller-sa # Name of Service Account to be created or used

rbac:
  create: true
  name: azuredisk

controller:
  name: csi-azuredisk-controller
  cloudConfigSecretName: azure-cloud-provider
  cloudConfigSecretNamespace: kube-system
  # featureGates allows you to enable or disable specific kubernetes features for different CSI components.
  # Enabling or disabling certain features may affect the behavior or capabilities of the driver.
  # # Example valid values:
  # featureGates:
  #   csiProvisioner: 
  #     - Topology=true                # Enables topology-aware volume provisioning
  #     - HonorPVReclaimPolicy=true    # Honors the reclaim policy set on PersistentVolumes
  #     - VolumeAttributesClass=true   # Enables support for VolumeAttributesClass
  #   csiResizer:
  #     - RecoverVolumeExpansionFailure=true  # Enables recovery from volume expansion failures
  #     - VolumeAttributesClass=true          # Enables support for VolumeAttributesClass
  featureGates:
    csiProvisioner:
      - Topology=true
      - HonorPVReclaimPolicy=true
      - VolumeAttributesClass=true
    csiResizer:
      - RecoverVolumeExpansionFailure=true
      - VolumeAttributesClass=true

  VMSSDetachTimeoutInSeconds: 20
  allowEmptyCloudConfig: false
  enableTrafficManager: false
  trafficManagerPort: 7788
  replicas: 2
  metricsPort: 29604
  livenessProbe:
    healthPort: 29602
  runOnMaster: false
  runOnControlPlane: false
  disableAvailabilitySetNodes: false
  vmType: ""
  provisionerWorkerThreads: 100
  attacherWorkerThreads: 1000
  vmssCacheTTLInSeconds: -1
  logLevel: 5
  extraArgs: []
  otelTracing:
    enabled: false
    otelServiceName: csi-azuredisk-controller
    otelExporterEndpoint: "http://localhost:4317"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/controlplane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"
  hostNetwork: true # this setting could be disabled if controller does not depend on MSI setting
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  nodeSelector: {}
  affinity: {}
  resources:
    csiProvisioner:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi
    csiAttacher:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi
    csiResizer:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi
    csiSnapshotter:
      limits:
        memory: 400Mi
      requests:
        cpu: 10m
        memory: 20Mi
    livenessProbe:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    azuredisk:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi

node:
  cloudConfigSecretName: azure-cloud-provider
  cloudConfigSecretNamespace: kube-system
  # reserved data disk slot number per node, driver.volumeAttachLimit must be < 0
  reservedDataDiskSlotNum: 0
  supportZone: true
  allowEmptyCloudConfig: true
  getNodeIDFromIMDS: false
  removeNotReadyTaint: true
  maxUnavailable: 1
  logLevel: 5
  metricsPort: 29605
  livenessProbe:
    healthPort: 29603

snapshot:
  enabled: false
  name: csi-snapshot-controller
  image:
    csiSnapshotter:
      repository: /oss/v2/kubernetes-csi/csi-snapshotter
      tag: v8.5.0
      pullPolicy: IfNotPresent
    csiSnapshotController:
      repository: /oss/v2/kubernetes-csi/snapshot-controller
      tag: v8.5.0
      pullPolicy: IfNotPresent
  snapshotController:
    name: csi-snapshot-controller
    replicas: 2
    labels: {}
    annotations: {}
    podLabels: {}
    podAnnotations: {}
    resources:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi
  VolumeSnapshotClass:
    enabled: false
    name: csi-azuredisk-vsc
    deletionPolicy: Delete
    parameters:
      incremental: '"true"' # available values: "true", "false" ("true" by default for Azure Public Cloud, and "false" by default for Azure Stack Cloud)
      resourceGroup: "" # available values: EXISTING RESOURCE GROUP (If not specified, snapshot will be stored in the same resource group as source Azure disk)
      tags: "" # tag format: 'key1=val1,key2=val2'
    additionalLabels: {}

feature:
  enableFSGroupPolicy: true

driver:
  name: disk.csi.azure.com
  # maximum number of attachable volumes per node,
  # maximum number is defined according to node instance type by default(-1)
  volumeAttachLimit: -1
  customUserAgent: ""
  userAgentSuffix: "OSS-helm"
  azureGoSDKLogLevel: "" # available values: ""(no logs), DEBUG, INFO, WARNING, ERROR
  httpsProxy: ""
  httpProxy: ""
  noProxy: ""

linux:
  enabled: true
  dsName: csi-azuredisk-node # daemonset name
  kubelet: /var/lib/kubelet
  distro: debian # available values: debian, fedora
  enablePerfOptimization: true
  otelTracing:
    enabled: false
    otelServiceName: csi-azuredisk-node
    otelExporterEndpoint: "http://localhost:4317"
  tolerations:
    - operator: "Exists"
  hostNetwork: true # this setting could be disabled if perfProfile is `none`
  getNodeInfoFromLabels: false # get node info from node labels instead of IMDS
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  nodeSelector: {}
  affinity: {}
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: NotIn
              values:
                - virtual-kubelet
  resources:
    livenessProbe:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    nodeDriverRegistrar:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    azuredisk:
      limits:
        memory: 1000Mi
      requests:
        cpu: 10m
        memory: 20Mi

windows:
  enabled: true
  useHostProcessContainers: true
  dsName: csi-azuredisk-node-win # daemonset name
  kubelet: 'C:\var\lib\kubelet'
  getNodeInfoFromLabels: false # get node info from node labels instead of IMDS
  enableRegistrationProbe: true
  otelTracing:
    enabled: false
    otelServiceName: csi-azuredisk-node-win
    otelExporterEndpoint: "http://localhost:4317"
  tolerations:
    - key: "node.kubernetes.io/os"
      operator: "Exists"
      effect: "NoSchedule"
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  nodeSelector: {}
  affinity: {}
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: NotIn
              values:
                - virtual-kubelet
  resources:
    livenessProbe:
      limits:
        memory: 150Mi
      requests:
        cpu: 10m
        memory: 40Mi
    nodeDriverRegistrar:
      limits:
        memory: 150Mi
      requests:
        cpu: 30m
        memory: 40Mi
    azuredisk:
      limits:
        memory: 1000Mi
      requests:
        cpu: 10m
        memory: 40Mi

cloud: AzurePublicCloud

## Reference to one or more secrets to be used when pulling images
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
imagePullSecrets: []
# - name: "image-pull-secret"

workloadIdentity:
  clientID: ""
  # [optional] If the AAD application or user-assigned managed identity is not in the same tenant as the cluster
  # then set tenantID with the application or user-assigned managed identity tenant ID
  tenantID: ""

azureCredentialFileConfigMap: azure-cred-file
