apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: azuredisk-volume-snapshot
spec:
  snapshotClassName: csi-azuredisk-vsc
  source:
    name: pvc-azuredisk
    kind: PersistentVolumeClaim
